import type { Octokit } from "@octokit/rest";
import type { PRContext, PRReviewData } from "../types";

const BOT_MARKER = "<!-- preel-video-review -->";

export async function postVideoComment(
  octokit: Octokit,
  ctx: PRContext,
  videoUrl: string,
  review: PRReviewData,
): Promise<void> {
  const body = buildCommentBody(videoUrl, review);

  // Check for existing bot comment to update
  const existing = await findExistingComment(octokit, ctx);

  if (existing) {
    await octokit.issues.updateComment({
      owner: ctx.owner,
      repo: ctx.repo,
      comment_id: existing,
      body,
    });
    console.log(`Updated existing comment ${existing} on PR #${ctx.prNumber}`);
  } else {
    await octokit.issues.createComment({
      owner: ctx.owner,
      repo: ctx.repo,
      issue_number: ctx.prNumber,
      body,
    });
    console.log(`Posted new comment on PR #${ctx.prNumber}`);
  }
}

async function findExistingComment(
  octokit: Octokit,
  ctx: PRContext,
): Promise<number | null> {
  const { data: comments } = await octokit.issues.listComments({
    owner: ctx.owner,
    repo: ctx.repo,
    issue_number: ctx.prNumber,
    per_page: 50,
  });

  const botComment = comments.find(
    (c) => c.body?.includes(BOT_MARKER),
  );

  return botComment?.id ?? null;
}

function buildCommentBody(videoUrl: string, review: PRReviewData): string {
  const sentimentEmoji =
    review.overallSentiment === "positive"
      ? ":white_check_mark:"
      : review.overallSentiment === "neutral"
        ? ":arrow_right:"
        : review.overallSentiment === "cautious"
          ? ":warning:"
          : ":rotating_light:";

  const risksSection =
    review.risks.length > 0
      ? `\n### Callouts\n${review.risks.map((r) => `- **${r.severity}** (${r.category}): ${r.description}`).join("\n")}\n`
      : "";

  const fileDetails = review.fileReviews
    .map(
      (f) =>
        `- **${f.filename}** (${f.significance}): ${f.purpose}`,
    )
    .join("\n");

  return `${BOT_MARKER}
## Preel Video Review

${sentimentEmoji} **${review.overallSentiment.charAt(0).toUpperCase() + review.overallSentiment.slice(1)}** — ${review.summary}

https://github.com/user-attachments/assets/${videoUrl}

${risksSection}
<details>
<summary>File-by-file breakdown</summary>

${fileDetails}

</details>

---
<sub>Generated by [preel](https://github.com/syntaxsdev/preel) — automated video reviews for PRs</sub>
`;
}
