import type { Octokit } from "@octokit/rest";

export interface PRComment {
  id: number;
  author: string;
  authorAvatarUrl: string;
  body: string;
  isBot: boolean;
  tool: string | null; // "coderabbit", "codex", "claude", "copilot", etc.
  createdAt: string;
  // For inline review comments
  file?: string;
  line?: number;
}

export interface PRReviewVerdict {
  author: string;
  state: "APPROVED" | "CHANGES_REQUESTED" | "COMMENTED" | "DISMISSED";
  body: string;
  isBot: boolean;
  tool: string | null;
}

export interface PRDiscussion {
  comments: PRComment[];
  reviews: PRReviewVerdict[];
  toolsInvolved: string[];
  humanReviewers: string[];
  hasApproval: boolean;
  hasChangesRequested: boolean;
}

// Known review bot patterns — login or app slug → tool name
const BOT_PATTERNS: [RegExp, string][] = [
  [/coderabbit/i, "CodeRabbit"],
  [/codex/i, "Codex"],
  [/claude/i, "Claude"],
  [/copilot/i, "Copilot"],
  [/deepsource/i, "DeepSource"],
  [/sonarcloud/i, "SonarCloud"],
  [/sonarqube/i, "SonarQube"],
  [/snyk/i, "Snyk"],
  [/dependabot/i, "Dependabot"],
  [/renovate/i, "Renovate"],
  [/codecov/i, "Codecov"],
  [/github-actions/i, "GitHub Actions"],
  [/preel/i, "Preel"],
];

function detectTool(login: string, body: string): string | null {
  for (const [pattern, name] of BOT_PATTERNS) {
    if (pattern.test(login)) return name;
  }
  // Check body for tool signatures
  if (body.includes("<!-- coderabbit")) return "CodeRabbit";
  if (body.includes("<!-- codex")) return "Codex";
  if (body.includes("Generated by Claude")) return "Claude";
  if (body.includes("<!-- copilot")) return "Copilot";
  return null;
}

function isBot(type: string | undefined, login: string): boolean {
  if (type === "Bot") return true;
  if (login.endsWith("[bot]")) return true;
  if (login === "dependabot" || login === "renovate") return true;
  return false;
}

/** Strip HTML comments, excessive markdown, and collapse whitespace */
function cleanBody(body: string, maxLen = 2000): string {
  let cleaned = body
    .replace(/<!--[\s\S]*?-->/g, "") // HTML comments
    .replace(/\<details\>[\s\S]*?\<\/details\>/gi, "[collapsed section]") // collapsed sections
    .replace(/```[\s\S]*?```/g, "[code block]") // code blocks → placeholder
    .replace(/\n{3,}/g, "\n\n") // collapse newlines
    .trim();
  if (cleaned.length > maxLen) {
    cleaned = cleaned.slice(0, maxLen) + "...";
  }
  return cleaned;
}

export async function fetchPRDiscussion(
  octokit: Octokit,
  owner: string,
  repo: string,
  prNumber: number,
  maxComments = 50,
): Promise<PRDiscussion> {
  // Fetch issue comments and review comments in parallel
  const [issueComments, reviewComments, reviews] = await Promise.all([
    octokit.issues.listComments({
      owner, repo, issue_number: prNumber, per_page: 100,
    }),
    octokit.pulls.listReviewComments({
      owner, repo, pull_number: prNumber, per_page: 100,
    }),
    octokit.pulls.listReviews({
      owner, repo, pull_number: prNumber, per_page: 50,
    }),
  ]);

  const comments: PRComment[] = [];

  // Issue-level comments (general discussion)
  for (const c of issueComments.data) {
    const login = c.user?.login ?? "unknown";
    const bot = isBot(c.user?.type, login);
    const tool = detectTool(login, c.body ?? "");

    // Skip our own comments
    if (tool === "Preel") continue;

    comments.push({
      id: c.id,
      author: login,
      authorAvatarUrl: c.user?.avatar_url ?? "",
      body: cleanBody(c.body ?? ""),
      isBot: bot,
      tool,
      createdAt: c.created_at,
    });
  }

  // Inline review comments (on specific lines)
  for (const c of reviewComments.data) {
    const login = c.user?.login ?? "unknown";
    const bot = isBot(c.user?.type, login);
    const tool = detectTool(login, c.body ?? "");

    if (tool === "Preel") continue;

    comments.push({
      id: c.id,
      author: login,
      authorAvatarUrl: c.user?.avatar_url ?? "",
      body: cleanBody(c.body ?? "", 500),
      isBot: bot,
      tool,
      createdAt: c.created_at,
      file: c.path,
      line: c.line ?? c.original_line ?? undefined,
    });
  }

  // Sort by date, take most recent
  comments.sort((a, b) => new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime());
  const limited = comments.slice(0, maxComments);

  // Review verdicts
  const reviewVerdicts: PRReviewVerdict[] = reviews.data
    .filter((r) => r.state !== "PENDING")
    .map((r) => {
      const login = r.user?.login ?? "unknown";
      const bot = isBot(r.user?.type, login);
      const tool = detectTool(login, r.body ?? "");
      return {
        author: login,
        state: r.state as PRReviewVerdict["state"],
        body: cleanBody(r.body ?? "", 500),
        isBot: bot,
        tool: tool === "Preel" ? null : tool,
      };
    });

  // Collect metadata
  const toolsInvolved = [...new Set(
    [...limited, ...reviewVerdicts]
      .map((c) => c.tool)
      .filter((t): t is string => t !== null),
  )];

  const humanReviewers = [...new Set(
    [...limited, ...reviewVerdicts]
      .filter((c) => !c.isBot)
      .map((c) => c.author),
  )];

  const hasApproval = reviewVerdicts.some((r) => r.state === "APPROVED");
  const hasChangesRequested = reviewVerdicts.some((r) => r.state === "CHANGES_REQUESTED");

  return {
    comments: limited,
    reviews: reviewVerdicts,
    toolsInvolved,
    humanReviewers,
    hasApproval,
    hasChangesRequested,
  };
}

/** Build a text summary of the discussion for feeding to the LLM */
export function buildDiscussionText(discussion: PRDiscussion, maxChars = 30_000): string {
  if (discussion.comments.length === 0 && discussion.reviews.length === 0) {
    return "";
  }

  let text = "\n\n--- PR Discussion ---\n";

  // Review verdicts first
  if (discussion.reviews.length > 0) {
    text += "\nReview verdicts:\n";
    for (const r of discussion.reviews) {
      const tag = r.tool ? ` (${r.tool})` : r.isBot ? " (bot)" : "";
      text += `- ${r.author}${tag}: ${r.state}`;
      if (r.body) text += ` — "${r.body.slice(0, 200)}"`;
      text += "\n";
    }
  }

  // Tools involved
  if (discussion.toolsInvolved.length > 0) {
    text += `\nReview tools used: ${discussion.toolsInvolved.join(", ")}\n`;
  }

  // Comments grouped by author
  text += "\nComments:\n";
  for (const c of discussion.comments) {
    if (text.length > maxChars) {
      text += `\n... (${discussion.comments.length - discussion.comments.indexOf(c)} more comments truncated)\n`;
      break;
    }
    const tag = c.tool ? ` (${c.tool})` : c.isBot ? " (bot)" : "";
    const loc = c.file ? ` [${c.file}${c.line ? `:${c.line}` : ""}]` : "";
    text += `\n${c.author}${tag}${loc}:\n${c.body}\n`;
  }

  return text;
}
