import React from "react";
import {
  AbsoluteFill,
  useCurrentFrame,
  useVideoConfig,
  interpolate,
} from "remotion";
import { COLORS, FONTS, springEntrance } from "../styles";

interface SummaryProps {
  summary: string;
  overallSentiment: "positive" | "neutral" | "cautious" | "concerning";
  stats: {
    totalAdditions: number;
    totalDeletions: number;
    filesChanged: number;
  };
  risksCount: number;
}

const SENTIMENT_CONFIG: Record<
  string,
  { color: string; bg: string; label: string; icon: string }
> = {
  positive: {
    color: COLORS.green,
    bg: `${COLORS.green}15`,
    label: "Looks Good",
    icon: "✓",
  },
  neutral: {
    color: COLORS.blue,
    bg: `${COLORS.blue}15`,
    label: "Straightforward",
    icon: "→",
  },
  cautious: {
    color: COLORS.amber,
    bg: `${COLORS.amber}15`,
    label: "Review Carefully",
    icon: "△",
  },
  concerning: {
    color: COLORS.red,
    bg: `${COLORS.red}15`,
    label: "Needs Attention",
    icon: "!",
  },
};

export const Summary: React.FC<SummaryProps> = ({
  summary,
  overallSentiment,
  stats,
  risksCount,
}) => {
  const frame = useCurrentFrame();
  const { fps, durationInFrames } = useVideoConfig();

  const sentiment = SENTIMENT_CONFIG[overallSentiment] || SENTIMENT_CONFIG.neutral;
  const badge = springEntrance(frame, fps, 0);
  const text = springEntrance(frame, fps, 10);
  const footer = springEntrance(frame, fps, 18);

  // Fade out at end
  const fadeOut = interpolate(
    frame,
    [durationInFrames - 20, durationInFrames],
    [1, 0],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" },
  );

  return (
    <AbsoluteFill
      style={{
        backgroundColor: COLORS.bg,
        padding: "80px 100px",
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "center",
        opacity: fadeOut,
      }}
    >
      {/* Sentiment badge */}
      <div
        style={{
          opacity: badge.opacity,
          transform: `translateY(${badge.translateY}px) scale(${0.8 + badge.opacity * 0.2})`,
          display: "flex",
          alignItems: "center",
          gap: 16,
          padding: "16px 36px",
          borderRadius: 16,
          background: sentiment.bg,
          border: `2px solid ${sentiment.color}40`,
          marginBottom: 48,
        }}
      >
        <span
          style={{
            fontFamily: FONTS.mono,
            fontSize: 36,
            color: sentiment.color,
            fontWeight: 700,
          }}
        >
          {sentiment.icon}
        </span>
        <span
          style={{
            fontFamily: FONTS.sans,
            fontSize: 32,
            fontWeight: 700,
            color: sentiment.color,
          }}
        >
          {sentiment.label}
        </span>
      </div>

      {/* Summary text */}
      <div
        style={{
          opacity: text.opacity,
          transform: `translateY(${text.translateY}px)`,
          fontFamily: FONTS.sans,
          fontSize: 30,
          color: COLORS.text,
          lineHeight: 1.5,
          textAlign: "center",
          maxWidth: 1200,
          marginBottom: 64,
        }}
      >
        {summary}
      </div>

      {/* Quick stats */}
      <div
        style={{
          opacity: footer.opacity,
          transform: `translateY(${footer.translateY}px)`,
          display: "flex",
          gap: 48,
          fontFamily: FONTS.mono,
          fontSize: 20,
          color: COLORS.textSecondary,
        }}
      >
        <span>
          <span style={{ color: COLORS.green }}>+{stats.totalAdditions}</span>{" "}
          <span style={{ color: COLORS.red }}>−{stats.totalDeletions}</span>
        </span>
        <span>
          {stats.filesChanged} file{stats.filesChanged !== 1 ? "s" : ""}
        </span>
        {risksCount > 0 && (
          <span style={{ color: COLORS.amber }}>
            {risksCount} callout{risksCount !== 1 ? "s" : ""}
          </span>
        )}
      </div>

      {/* Brand footer */}
      <div
        style={{
          position: "absolute",
          bottom: 48,
          display: "flex",
          alignItems: "center",
          gap: 12,
        }}
      >
        <span
          style={{
            fontFamily: FONTS.sans,
            fontSize: 18,
            color: COLORS.textMuted,
            letterSpacing: 2,
          }}
        >
          Generated by
        </span>
        <span
          style={{
            fontFamily: FONTS.sans,
            fontSize: 20,
            fontWeight: 700,
            color: COLORS.accent,
            letterSpacing: 2,
          }}
        >
          PREEL
        </span>
      </div>
    </AbsoluteFill>
  );
};
